_target_: oslow.training.permutation_learning.buffered_methods.GumbelTopK
_partial_: true
initialization_function:
  _target_: oslow.training.permutation_learning.initialization.uniform_gamma_init_func
  mode: permutation-matrix
  _partial_: true

num_samples: ${data.num_samples}
buffer_size: 10
buffer_update: 10