logging_scatterplot_frequency: 1
train_fixed: false

_target_: oslow.ensemble.EnsembleTrainer
_partial_: true
device: cuda
perm_list: ${get_permutations:${data.graph_generator.num_nodes}}

max_epochs: 50

flow_optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  _partial_: true

flow_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  _partial_: true
