_target_: oslow.plackett_luce.PlackettLuceTrainer
_partial_: true
device: cuda


max_epochs: 400

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  _partial_: true


perm_expectation_b_size: 16

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  _partial_: true
