defaults:
  - data: default
  - model: misspecified
  - trainer: default
  - hydra: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

wandb:
  run_name: order_discovery
  project: order_discovery
  entity: ordered-causal-discovery

flow_batch_size: 128
permutation_batch_size: 128

test_run: false
out_dir: runs/
