defaults:
  - data: default
  - model: specified
  - trainer: ensemble
  - hydra: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

wandb:
  run_name: ensemble
  project: ensemble

flow_batch_size: 128
flow_ensemble_batch_size: 128

test_run: false
out_dir: runs/
