defaults:
  - data: default
  - model: affine_specified
  - trainer: plackett_luce
  - hydra: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

wandb:
  run_name: plackett_luce_
  project: plackett_luce

batch_size: 64

test_run: false
out_dir: runs/
